Refactor pmm-system calls in pmm-info

diff --git a/bin/pmm-info b/bin/pmm-info
--- a/bin/pmm-info
+++ b/bin/pmm-info
@@ -18,7 +18,8 @@ _info_version() {
 
 
 _info_os_arch() {
-    case "$(pmm system os-name)" in
+    os_name="$(pmm system os-name)"
+    case "${os_name}" in
         debian|ubuntu|trisquel)
             echo $(dpkg --print-architecture)
         ;;
@@ -28,19 +29,21 @@ _info_os_arch() {
             elif [ -f /lib/libc.so.6 ]; then
                 echo "i386"
             else
+                echo 1>&2 "E: Unknown operating system architecture"
                 echo ""
             fi
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_name}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_os_package_manager() {
-    case "$(pmm system os-name)" in
+    os_name="$(pmm system os-name)"
+    case "${os_name}" in
         debian|ubuntu|trisquel)
             echo "apt-get"
         ;;
@@ -51,15 +54,16 @@ _info_os_package_manager() {
             echo "zypper"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_name}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_hdf4() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-[45].0*)
             echo "libhdf4g libhdf4g-dev"
         ;;
@@ -73,15 +77,16 @@ _info_hdf4() {
             echo "libhdf4 hdf-devel hdf-devel-static"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_hdf5() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-4.0*)
             echo "libhdf5-serial-1.6.5-0 libhdf5-serial-dev"
         ;;
@@ -98,15 +103,16 @@ _info_hdf5() {
             echo "libhdf5 hdf5-devel hdf5-devel-static"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_blas() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-4.0*)
             echo "refblas3 refblas3-dev"
         ;;
@@ -123,15 +129,16 @@ _info_blas() {
             echo "libblas3 blas-devel blas-devel-static"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_lapack() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-4.0*)
             echo "lapack3 lapack3-dev"
         ;;
@@ -148,15 +155,16 @@ _info_lapack() {
             echo "liblapack3 lapack-devel lapack-devel-static"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_netcdf4() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-5.0*)
             echo "libnetcdf4 libnetcdf-dev"
         ;;
@@ -170,15 +178,16 @@ _info_netcdf4() {
             echo "libnetcdf18 netcdf-devel netcdf-devel-static"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_matplotlib_dev() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-[45].0*)
             echo "libfreetype6-dev libpng12-dev"
         ;;
@@ -192,8 +201,8 @@ _info_matplotlib_dev() {
             echo "freetype-devel libpng16-devel"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
@@ -206,7 +215,7 @@ _info_openssl_root() {
     fi
     regex="1\.(0\.2[a-u]?|1\.1[a-k]?)"
     if [ -z $(echo "${version}" | grep -E "^${regex}$" || true) ]; then
-        echo "E: Invalid openssl version '$1'"
+        echo 1>&2 "E: Invalid openssl version '$1'"
         exit 1
     fi
     version_short=$(echo ${version} | sed -r 's|(([0-9]\.)+[0-9])[a-z]?|\1|g')
@@ -215,7 +224,8 @@ _info_openssl_root() {
 
 
 _info_gcc_full() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-[45].0*|ubuntu-*|trisquel-*)
             echo "gcc g++ gfortran"
         ;;
@@ -226,15 +236,16 @@ _info_gcc_full() {
             echo "gcc gcc-c++ gcc-fortran"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_pkg_config() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-[45].0*|ubuntu-*|trisquel-*|opensuse*-*|sles-*)
             echo "pkg-config"
         ;;
@@ -242,15 +253,16 @@ _info_pkg_config() {
             echo "pkgconfig"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_libffi() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-4.0*)
             echo "libffi4"
         ;;
@@ -273,15 +285,16 @@ _info_libffi() {
             echo "libffi"
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
 
 
 _info_pyenv_dev() {
-    case "$(pmm system os-name)-$(pmm system os-version)" in
+    os_fullname="$(pmm system os-name)-$(pmm system os-version)"
+    case "${os_fullname}" in
         debian-4.0*)
             echo "
                 build-essential libncursesw5-dev libreadline-dev              \
@@ -308,8 +321,8 @@ _info_pyenv_dev() {
             " | xargs
         ;;
         *)
-            echo "E: Unknown operating system '$(pmm system os-name)-$(pmm system os-version)'"
-            exit 1
+            echo 1>&2 "E: Unknown operating system '${os_fullname}'"
+            echo ""
         ;;
     esac
 }
@@ -378,7 +391,7 @@ case "$1" in
         _info_$(echo $1 | tr - _)
     ;;
     *)
-        echo "E: Unknown option '$1'"
+        echo 1>&2 "E: Unknown ${name} option: '$1'"
         exit 1
     ;;
 esac
